### ISSUE TITLE
Auth0

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-platform#152]
TODO list for finishing the Auth0 work:

* [x] user newsletter (Jana)
* [x] Is Keycloak going to be able to handle the load? #171  (using 1, that means 100%)
* [x] adapt lumen cypress tests to auth0 https://github.com/akvo/akvo-lumen/issues/2378
* [x] internal update to Akvo Core about Auth0 changes (Jana)
* [X] Add all "Allowed Web Origins" to auth0 settings, using this list https://docs.google.com/spreadsheets/d/1YyepMjfwdL1263_kAsBq4FQ3fsiqWSHVHJEWPCEWZdg/edit#gid=1675419055
* [x] deploy Auth0 to a few Flow instances to start with and then next - create a list (Jana) https://github.com/akvo/akvo-flow-server-config/issues/531
* [x] Test session expiration in Flow and Lumen https://github.com/akvo/akvo-platform/issues/168
* [x] Do we need to do link accounts in Auth0? https://github.com/akvo/akvo-platform/issues/181 
* [x] Add french translations to unauthorized page in flow https://github.com/akvo/akvo-flow/pull/3207 for addding log out option for Flow and Lumen when a user logs in but tries to access an instance she/he does not have access to  (https://github.com/akvo/akvo-lumen/issues/2346)
* [x] Add email verification error page for Lumen and Flow (should be the same)
* [x] What to do with the dev env? Both Flow and Lumen https://github.com/akvo/akvo-platform/issues/167  (Not for the first release)
* [x] Cache in Lumen https://github.com/akvo/akvo-lumen/issues/2307
* [x] Sign up in Auth0 flow: disable user access until email confirmation. Needs to be handled by Lumen and Flow, or find a way for Auth0 to not redirect to Flow/Lumen until the user has done the email confirmation. https://github.com/akvo/akvo-platform/issues/154 . [Lumen side done](https://github.com/akvo/akvo-lumen/pull/2260) 
[Flow side](https://github.com/akvo/akvo-flow/pull/3194)
* [x] Languages of Login page. check => https://auth0.com/docs/universal-login/i18n
* [x] Configure email provider in Auth0 https://github.com/akvo/akvo-platform/issues/165
* [x] Configure production 
  * [x] Set up a auth0 production tenant 
  * [x] Set up akvo-flow-api-internal 
  * [x] Configure platform env vars  
  * [x] Configure/test lumen  
  * [x] Configure/test flow https://github.com/akvo/akvo-flow-server-config/pull/527

* [x] Review tenant creation script [relates https://github.com/akvo/akvo-lumen/issues/2247 & https://github.com/akvo/akvo-lumen/pull/2298]
* [x] Add internal service for flow-api https://github.com/akvo/akvo-flow-api/issues/179  (Not for the first release)
* [x] Single sign out (Not for the first release)
* [x] OIDC client, how many do we really need? https://github.com/akvo/akvo-platform/issues/166
* [x] Branding of OAUTH consent page https://github.com/akvo/akvo-platform/issues/155
* [x] Branding of Login page #153
* [x] Migration of Lumen users?
* [ ] Migration of Flow API users? (Needs to happen, but not as part of the first release)
* [x] Give Loic permissions in Auth0 for rebranding.
* [x] Do we need user admins in Auth0? (No needed)
Please, add more details to know what are we meaning here. So far, the admin attribute of the user is stored in keycloak and it's used for inviting/promoting/demoting/removing users from current tenant

* [x] Branding of emails (password recovery, email confirmation, …)
* [x] Users with the same email but login with gmail and user/passwd
_IMO this is working properly_
* [x] Updated the Google consent screen with Akvo's logo. Use the Twitter logo as it is also rounded. Remember that after updating the logo, the OAuth consent screen must be verified again by Google.

**Comment by janagombitova** [comment]
@tangrammer are we ready to close this issue?

**Comment by kardan** [comment]
Still working on E2E tests.

**Comment by dlebrero** [comment]
Close now?

**Comment by tangrammer** [comment]
maybe wait until the external clients/partners could finally use it 🤔

**Comment by dlebrero** [comment]
I think @iperdomo has already done that?
